version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./home:/config
    ports:
      - 8080:80
      - 8443:443
    mem_limit: 1GB
    restart: unless-stopped