version: "2.1"
services:
    webtop:
        image: raychorn/linuxserver_webtop:ubuntu-kde #ghcr.io/linuxserver/webtop:ubuntu-kde
        container_name: webtop
        privileged: true
        environment:
            - PUID=0
            - PGID=0
            - TZ=America/Denver
        volumes:
            - ./home:/config
            - /home/raychorn/projects/securex.ai:/securex.ai
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 3000:3000
        shm_size: "1gb"
        mem_limit: 4GB
        restart: unless-stopped